<a href="https://colab.research.google.com/github/RajeshRanaGiet/DMPM-Lab/blob/main/Experiment%203/LAB_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Numpy
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)
print(arr.mean(), arr.sum(), arr.max(), arr.min())
print(arr.shape)

[10 20 30 40 50]
30.0 150 50 10
(5,)


In [2]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
arr1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
arr2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print("The sum is :-\n", arr1+arr2)
print("\nThe subrtaction is :-\n", arr1-arr2)
print("\nThe multiplication is :-\n", arr1*arr2)
print("\nThe division is :-\n", arr1/arr2)


The division is :-
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
import pandas as pd
data = pd.read_csv("")
data.head()